### ISSUE TITLE
Allow export of interpolation coefficients

### ISSUE THREAD

**Issue by ChristopherRabotin** [aftix/bacon#3]
There are use cases where one wants to generate an interpolation, save it into some data structure, and then reload this interpolation to recreate an interpolator. In my case, I want to create a Lagrange interpolation of a trajectory, export these coefficients, and then reuse them later.

**Comment by aftix** [comment]
I closed the pull request, but you can also rebuild polynomials by enabling the serde feature to serialize/deserialize

**Comment by ChristopherRabotin** [comment]
Hi there,
Any chance you could publish the updated version of bacon-sci? My crate depends on the latest version, and I can't publish it until you've published an updated version.

```
$ cargo publish
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `bacon-sci` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

Thanks

**Comment by aftix** [comment]
Version 0.11.0 has been released. How are you depending on bacon-sci? I think this is a problem of you specifying the version as "*" and not as a concrete one.

**Comment by ChristopherRabotin** [comment]
Thanks. I depend on bacon-sci for the Lagrange interpolation of spacecraft trajectories in [nyx](https://gitlab.com/nyx-space/nyx). The interpolated trajectory is used for trajectory analysis and some cool plots, like [this](https://nyxspace.com/showcase/mission_design/orbit_design_ga/#case-0).

Good reminder. I always specify specific versions of dependencies.
